### ISSUE TITLE
making it work with spring boot 2.7.6 and java 1.8

### ISSUE THREAD

**Issue by ccampisano** [spring-guides/gs-vault-config#18] opened 2022-12-23 08:20 UTC
Hello,
I have a project using java 1.8 and spring boot 2.7.6, which should now support vault.

I setup vault with the UI:
![00 - vault configuration](https://user-images.githubusercontent.com/120666584/209299279-5cadde37-4c57-4cdf-acfb-3845c94feecb.png)

Main branch version doesn't work on java 1.8:
![01 - main branch](https://user-images.githubusercontent.com/120666584/209299163-a6ed203a-fe09-4911-a13f-ea749df0bcfa.png)

so I switched to version 2.1.6.RELEASE:
![02 - new branch based on 2 1 6](https://user-images.githubusercontent.com/120666584/209299327-9beb1355-6fe5-49e8-810c-f09f96890b96.png)

and version 2.1.6.RELEASE does work fine:
![03 - release 2 1 6 works fine](https://user-images.githubusercontent.com/120666584/209299390-230974ed-db04-4c80-b188-f914acc37727.png)

but if I try to change sb version to 2.7.6 it fails:
![04 - not working when upgrading to 2 7 6](https://user-images.githubusercontent.com/120666584/209299739-c749df74-16fc-4e36-9e0d-68d030e91ef1.png)

should I update the "spring-cloud.version" too?

I recall I saw a list of compatible versions somewhere, but can't recall where.

PS: here's the error log:
[error log.txt](https://github.com/spring-guides/gs-vault-config/files/10293530/error.log.txt)

thanks
corrado

**Comment by ccampisano** [comment] 2022-12-23 08:51
I was referring to [this spring-cloud documentation link](https://spring.io/projects/spring-cloud)

I tried 2021.0.5, 2021.0.4 and 2021.0.3, no more exceptions, but they all return "null", how to fix this?

![02 - fails retrurning null with 2021 0 4](https://user-images.githubusercontent.com/120666584/209304419-5be85ea4-cb44-4ce8-8540-1efdc6e660a1.png)
![03 - fails retrurning null with 2021 0 3](https://user-images.githubusercontent.com/120666584/209304423-5c464e89-34d9-4e4c-a6ca-69a6abe56cff.png)
![01 - fails retrurning null with 2021 0 5](https://user-images.githubusercontent.com/120666584/209304427-b778378a-541e-486e-a4b7-00b2c786d9f2.png)

thanks
corrado

**Comment by robertmcnees** [comment] 2024-07-09 11:42
Hi @ccampisano. This guide had a major rewrite with PR #19, including updating to the latest Java, Spring Boot, and Spring Cloud versions. The issue here should be addressed in that update and live now.

I will close this issue but please feel free to open another issue or continue the discussion here if the issue is not resolved.

**Closed as completed by robertmcnees** 2024-07-09 11:42 UTC
